### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by AdamDenoon** [jeboehm/docker-mailserver#39]
I have successfully run docker-mailerserver, and can access the web endpoints. I'm presented with a login page for the Web Manager, but upon login, I get a 403 (forbidden) error. The following appears in the logs for the web container:

`[18-May-2018 14:35:27] WARNING: [pool www] child 47 said into stderr: "2018-05-18T14:35:27+00:00 [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at /opt/manager/vendor/symfony/security/Http/Firewall/ExceptionListener.php line 117"`

No other containers log any errors.

**Comment by AdamDenoon** [comment]
I cloned it fresh yesterday.

If I remove the trailing slash, hit escape to remove auto-completion, and hit enter, the page reloads with 403 Forbidden and the slash re-appears at the end.

**Comment by AdamDenoon** [comment]
My docker-compose.yml is pulling the latest tags for all jeboehm images, also.

**Comment by jeboehm** [comment]
I tried to fix that issue in 4baa54.
To test it, checkout the branch bugfix/redirect, and run ```bin/production.sh build && bin/production.sh up -d```.

Anyway I'll merge that later so you can just pull the updated images.

Good luck!

**Comment by AdamDenoon** [comment]
I'm still having the same issue:

```
~/docker-mailserver$ cp docker-compose.yml ../dm-dc.yml
~/docker-mailserver$ cp .env ../dm-env
~/docker-mailserver$ git fetch; git reset --hard origin/master
~/docker-mailserver$ cp ../dm-env .env
~/docker-mailserver$ cp ../dm-dc.yml docker-compose.yml
~/docker-mailserver$ bin/production.sh build && bin/production.sh up -d
```

As before, I get redirected from www.myhost.com:81/manager to www.myhost.com:81/manager/login, but logging in brings me to www.myhost.com:81/manager. Any time I go to this page **after** logging in I get the 403.

**Comment by AdamDenoon** [comment]
For reference, here are my configuration files:

_NOTE: I'm using nginx-proxy with letsencrypt companion_
### docker-compose.yml (comments removed)
```YML
version: '3'

services:
  db:
    image: jeboehm/mailserver-db:latest
    build: ./db
    restart: on-failure:5
    env_file: .env
    volumes:
      - data-db:/var/lib/mysql

  mta:
    image: jeboehm/mailserver-mta:latest
    build: ./mta
    restart: on-failure:5
    env_file: .env
    volumes:
      - data-tls:/media/tls
      - /home/adam/mailcerts/cert.pem:/media/tls/mailserver.crt
      - /home/adam/mailcerts/key.pem:/media/tls/mailserver.key

  mda:
    image: jeboehm/mailserver-mda:latest
    build: ./mda
    restart: on-failure:5
    env_file: .env
    volumes:
      - data-mail:/var/vmail
      - data-tls:/media/tls
      - /home/adam/mailcerts/cert.pem:/media/tls/mailserver.crt
      - /home/adam/mailcerts/key.pem:/media/tls/mailserver.key

  web:
    image: jeboehm/mailserver-web:latest
    build: ./web
    restart: on-failure:5
    env_file: .env
    environment:
      - VIRTUAL_HOST=mail.myhost.com
      - LETSENCRYPT_HOST=mail.myhost.com # (SSL NOT WORKING at mail.myhost.com)
      - LETSENCRYPT_EMAIL=adam@myhost.com # (SSL NOT WORKING at mail.myhost.com)

  filter:
    image: jeboehm/mailserver-filter:latest
    build: ./filter
    restart: on-failure:5
    env_file: .env
    volumes:
      - data-filter:/var/lib/rspamd
    links:
      - virus:virus.local

  virus:
    image: jeboehm/mailserver-virus:latest
    build: ./virus
    restart: on-failure:5
    env_file: .env

volumes:
  data-db:
    driver: local
  data-mail:
    driver: local
  data-tls:
    driver: local
  data-filter:
    driver: local
```

### .env:
```
MYSQL_DATABASE=mailserver
MYSQL_USER=mailserver
MYSQL_PASSWORD=mytestpass
MYSQL_ROOT_PASSWORD=mytestrootpass
MAILNAME=mail.myhost.com
POSTMASTER=postmaster@myhost.com
FILTER_MIME=false
FILTER_VIRUS=true
ENABLE_IMAP=true
ENABLE_POP3=true
ADMIN_USERS=adam@myhost.com
CONTROLLER_PASSWORD=mytestcontrollerpassword
```
