### ISSUE TITLE
SSL for Web Container

### ISSUE THREAD

**Issue by AdamDenoon** [jeboehm/docker-mailserver#41]
Is there a way to get SSL active for the web container? I tried the standard nginx-proxy/LetsEncrypt Companion setup with no luck:

```YML
web:
    image: jeboehm/mailserver-web:latest
    build: ./web
    restart: on-failure:5
    env_file: .env
    environment:
      - VIRTUAL_HOST=mail.myhost.com
      - LETSENCRYPT_HOST=mail.myhost.com # (SSL NOT WORKING at mail.myhost.com)
      - LETSENCRYPT_EMAIL=adam@myhost.com # (SSL NOT WORKING at mail.myhost.com)
```

Is there a way to get this automatic process to work?

If not, is there a place I can mount existing SSL certs to, and force HTTPS?
