### ISSUE TITLE
Help wanted for local email client (e.g. Thunderbird)

### ISSUE THREAD

**Issue by kklepper** [jeboehm/docker-mailserver#82]
**Is your feature request related to a problem? Please describe.**

I had a running local connection to my domain hosted via plesk. Now I moved on to a virtual server and installed your system. Great work, great explanation, easy installation. Thank you very much.

Roundcube works, I could receive mail. I could not send due to a general lock of my new provider on port 25, which was removed on request. I also opened port 25 for connections from my local IP. Sending from Roundcube now works, too.

Now I wanted to change my local Thunderbird configuration to connect to my new virtual server. The domain name xxx.tld and mail.xxx.tld point to the new virtual server IP.  Well, no matter which method and port I choose for send and receive, I cannot send and I cannot receive from my local Thunderbird account like before. 

**Describe the solution you'd like**

I'd like to have a simple instruction to this end. What do I have to do where to make things work as expected.

**Describe alternatives you've considered**

I opened ports 25, 110, 143, 465, 587, 993, 995 - to no avail. Obviously I do not understand what I do.

**Additional context**

The old setting was 143 for receive and 587 for send.

This is an excerpt of my ports setting:

![image](https://user-images.githubusercontent.com/6130319/82328014-941e6c80-99df-11ea-82be-6e7c4b22d239.png)

As you see, I restricted one port to my local IP.

I set up a TLS certificate using letsencrypt, so https://xxx.tld works fine. Thunderbird comes up with

![image](https://user-images.githubusercontent.com/6130319/82327297-78ff2d00-99de-11ea-8bc4-cd160d9d58f5.png)

Downloading a certificate from here does not work either.

Sorry, I run out of ideas.

**Comment by jeboehm** [comment]
Hi @kklepper 

Thunderbird Settings for SMTP:
Port 587 with TLS/SSL (try both, if you have seperate options for this)
Authentification Method: Password

For incoming mails:
Port 143 with TLS
Authentification Method: Password

When LetsEncrypt is working, it is important to use the certificates in docker-mailserver aswell. [This guide](https://github.com/jeboehm/docker-mailserver/wiki/Howto:-Use-Your-Own-TLS-Certificates) should explain it. Don't forget to restart the whole project afterwards.

Roundcube is sending and receiving mails via an internal connection to the mda and mta service. What you need to open in your firewall are the ports 25 (for sending & receiving mails from external users), 143 (communication with your Thunderbird instance, receiving), 587 143 (communication with your Thunderbird instance, sending).

If it is all set up and working, I'ld appreciate if you can provide some documentation of your knowledge for other users.

**Comment by kklepper** [comment]
Thank you for your immediate answer. 

No error now, but timeout:

![image](https://user-images.githubusercontent.com/6130319/82334971-f760cc80-99e8-11ea-9d50-db4e7335b87a.png)

```
  # The Mail Transfer Agent (Postfix) receives incoming mail
  # on TCP port 25.
  mta:
    image: jeboehm/mailserver-mta:latest
    build: ./mta
    restart: on-failure:5
    env_file: .env
    volumes:
#      - data-tls:/media/tls:ro
      # For using external certificates uncomment the following lines
      # and change the path on the left side of the colon.
      # - /home/user/certs/mail.example.com.crt:/media/tls/mailserver.crt:ro
      # - /home/user/certs/mail.example.com.key:/media/tls/mailserver.key:ro
      - /etc/letsencrypt/archive/xxx.tld/fullchain1.pem:/media/tls/mailserver.crt:ro
      - /etc/letsencrypt/archive/xxx.tld/privkey1.pem:/media/tls/mailserver.key:ro

  # The Mail Delivery Agent (Dovecot) is responsible for storing
  # incoming mail into a users mailbox and also delivers them
  # via POP3 or IMAP4.
  mda:
    image: jeboehm/mailserver-mda:latest
    build: ./mda
    restart: on-failure:5
    env_file: .env
    volumes:
      - data-mail:/var/vmail
#      - data-tls:/media/tls:ro
      # For using external certificates uncomment the following lines
      # and change the path on the left side of the colon.
      # - /home/user/certs/mail.example.com.crt:/media/tls/mailserver.crt:ro
      # - /home/user/certs/mail.example.com.key:/media/tls/mailserver.key:ro
      - /etc/letsencrypt/archive/xxx.tld/fullchain1.pem:/media/tls/mailserver.crt:ro
      - /etc/letsencrypt/archive/xxx.tld/privkey1.pem:/media/tls/mailserver.key:ro

```
What's wrong here?
